/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\src\assets\flower.glb --transform --types 
Files: .\src\assets\flower.glb [1.88MB] > D:\yourcrush\flower-transformed.glb [486.79KB] (74%)
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pasted__inside071_pasted__leaf_0: THREE.Mesh;
    pasted__inside068_pasted__leaf_0: THREE.Mesh;
    petalsss001_petal1_0: THREE.Mesh;
    petalsss007_petal1_0: THREE.Mesh;
    petalsss011_petal3_0: THREE.Mesh;
    heart01_heart_0: THREE.Mesh;
    heart03_heart_0: THREE.Mesh;
    heart05_heart_0: THREE.Mesh;
    heart08_heart_0: THREE.Mesh;
    heart02_heart_0: THREE.Mesh;
    heart04_heart_0: THREE.Mesh;
    pasted__inside075_pasted__leaf_0: THREE.Mesh;
    petalsss002_petal1_0: THREE.Mesh;
    petalsss003_petal3_0: THREE.Mesh;
    petalsss012_petal1_0: THREE.Mesh;
    petalsss013_petal3_0: THREE.Mesh;
    pasted__inside067_pasted__leaf_0: THREE.Mesh;
    pasted__inside069_pasted__leaf_0: THREE.Mesh;
    pasted__inside072_pasted__leaf_0: THREE.Mesh;
    pasted__inside073_pasted__leaf_0: THREE.Mesh;
    pasted__inside076_pasted__leaf_0: THREE.Mesh;
    pasted__inside077_pasted__leaf_0: THREE.Mesh;
    pasted__inside078_pasted__leaf_0: THREE.Mesh;
    petalsss006_petal3_0: THREE.Mesh;
    petalsss008_petal3_0: THREE.Mesh;
    petalsss010_petal3_0: THREE.Mesh;
    pasted__bouque001_pasted__lower_0: THREE.Mesh;
    pasted__inside013_petal2_0: THREE.Mesh;
    pasted__inside018_pasted__leaf_0: THREE.Mesh;
    ["pasted__Line006_pasted__05_-_Default_0"]: THREE.Mesh;
    pasted__petal028_petal1_0: THREE.Mesh;
    pasted__petal036_petal3_0: THREE.Mesh;
    polySurface1_paper_0: THREE.Mesh;
    ribbon2_ribbon1_0: THREE.Mesh;
  };
  materials: {
    ["pasted__leaf.007"]: THREE.MeshStandardMaterial;
    ["petal1.004"]: THREE.MeshStandardMaterial;
    ["petal3.004"]: THREE.MeshStandardMaterial;
    ["heart.004"]: THREE.MeshStandardMaterial;
    ["pasted__lower.004"]: THREE.MeshStandardMaterial;
    ["petal2.004"]: THREE.MeshStandardMaterial;
    ["pasted__05_-_Default.004"]: THREE.MeshStandardMaterial;
    ["paper.004"]: THREE.MeshStandardMaterial;
    ["ribbon1.004"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "rotate";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/src/assets/flower-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      actions.rotate.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" scale={0.01}>
          <group name="group1" position={[-4.026, 0, -23.179]}>
            <group
              name="pasted__inside071"
              position={[-48.591, 19.206, 65.338]}
            >
              <mesh
                name="pasted__inside071_pasted__leaf_0"
                geometry={nodes.pasted__inside071_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="pasted__inside068">
              <mesh
                name="pasted__inside068_pasted__leaf_0"
                geometry={nodes.pasted__inside068_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="petalsss001">
              <mesh
                name="petalsss001_petal1_0"
                geometry={nodes.petalsss001_petal1_0.geometry}
                material={materials["petal1.004"]}
              />
            </group>
            <group name="petalsss007">
              <mesh
                name="petalsss007_petal1_0"
                geometry={nodes.petalsss007_petal1_0.geometry}
                material={materials["petal1.004"]}
              />
            </group>
            <group name="petalsss011">
              <mesh
                name="petalsss011_petal3_0"
                geometry={nodes.petalsss011_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
          </group>
          <group name="hearts" position={[18.013, 79.318, -5.879]}>
            <group name="heart01" position={[-65.333, -2.201, -42.84]}>
              <mesh
                name="heart01_heart_0"
                geometry={nodes.heart01_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
            <group name="heart03" position={[63.693, -9.665, 27.451]}>
              <mesh
                name="heart03_heart_0"
                geometry={nodes.heart03_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
            <group name="heart05" position={[24.039, 17.163, 5.274]}>
              <mesh
                name="heart05_heart_0"
                geometry={nodes.heart05_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
            <group name="heart08" position={[-15.817, -48.678, 49.522]}>
              <mesh
                name="heart08_heart_0"
                geometry={nodes.heart08_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
            <group name="heart02" position={[-37.023, 71.125, 36.951]}>
              <mesh
                name="heart02_heart_0"
                geometry={nodes.heart02_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
            <group name="heart04" position={[7.08, 39.132, -49.828]}>
              <mesh
                name="heart04_heart_0"
                geometry={nodes.heart04_heart_0.geometry}
                material={materials["heart.004"]}
              />
            </group>
          </group>
          <group name="petalss" position={[3.269, 57.716, -13.072]}>
            <group
              name="pasted__inside075"
              position={[-44.089, -4.539, 72.938]}
            >
              <mesh
                name="pasted__inside075_pasted__leaf_0"
                geometry={nodes.pasted__inside075_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="petalsss002" position={[7.347, 17.67, -49.198]}>
              <mesh
                name="petalsss002_petal1_0"
                geometry={nodes.petalsss002_petal1_0.geometry}
                material={materials["petal1.004"]}
              />
            </group>
            <group name="petalsss003" position={[13.361, 55.727, 40.543]}>
              <mesh
                name="petalsss003_petal3_0"
                geometry={nodes.petalsss003_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
            <group name="petalsss012" position={[-50.496, 19.988, 75.314]}>
              <mesh
                name="petalsss012_petal1_0"
                geometry={nodes.petalsss012_petal1_0.geometry}
                material={materials["petal1.004"]}
              />
            </group>
            <group name="petalsss013" position={[23.64, -11.848, -73.917]}>
              <mesh
                name="petalsss013_petal3_0"
                geometry={nodes.petalsss013_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
            <group name="pasted__inside067" position={[7.051, 45.315, -4.932]}>
              <mesh
                name="pasted__inside067_pasted__leaf_0"
                geometry={nodes.pasted__inside067_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="pasted__inside069" position={[17.643, 78.9, 55.411]}>
              <mesh
                name="pasted__inside069_pasted__leaf_0"
                geometry={nodes.pasted__inside069_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group
              name="pasted__inside072"
              position={[57.675, -59.043, 45.155]}
            >
              <mesh
                name="pasted__inside072_pasted__leaf_0"
                geometry={nodes.pasted__inside072_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="pasted__inside073" position={[7.051, -59.599, -4.932]}>
              <mesh
                name="pasted__inside073_pasted__leaf_0"
                geometry={nodes.pasted__inside073_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group
              name="pasted__inside076"
              position={[-44.089, -4.539, -78.928]}
            >
              <mesh
                name="pasted__inside076_pasted__leaf_0"
                geometry={nodes.pasted__inside076_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="pasted__inside077" position={[-4.616, 2.955, -56.82]}>
              <mesh
                name="pasted__inside077_pasted__leaf_0"
                geometry={nodes.pasted__inside077_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group
              name="pasted__inside078"
              position={[-85.261, -14.573, 11.319]}
            >
              <mesh
                name="pasted__inside078_pasted__leaf_0"
                geometry={nodes.pasted__inside078_pasted__leaf_0.geometry}
                material={materials["pasted__leaf.007"]}
              />
            </group>
            <group name="petalsss006" position={[42.293, 71.384, 28.084]}>
              <mesh
                name="petalsss006_petal3_0"
                geometry={nodes.petalsss006_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
            <group name="petalsss008" position={[49.471, -70.606, -12.738]}>
              <mesh
                name="petalsss008_petal3_0"
                geometry={nodes.petalsss008_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
            <group name="petalsss010" position={[42.293, -33.53, 28.084]}>
              <mesh
                name="petalsss010_petal3_0"
                geometry={nodes.petalsss010_petal3_0.geometry}
                material={materials["petal3.004"]}
              />
            </group>
          </group>
        </group>
        <mesh
          name="pasted__bouque001_pasted__lower_0"
          geometry={nodes.pasted__bouque001_pasted__lower_0.geometry}
          material={materials["pasted__lower.004"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="pasted__inside013_petal2_0"
          geometry={nodes.pasted__inside013_petal2_0.geometry}
          material={materials["petal2.004"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="pasted__inside018_pasted__leaf_0"
          geometry={nodes.pasted__inside018_pasted__leaf_0.geometry}
          material={materials["pasted__leaf.007"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="pasted__Line006_pasted__05_-_Default_0"
          geometry={nodes["pasted__Line006_pasted__05_-_Default_0"].geometry}
          material={materials["pasted__05_-_Default.004"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="pasted__petal028_petal1_0"
          geometry={nodes.pasted__petal028_petal1_0.geometry}
          material={materials["petal1.004"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="pasted__petal036_petal3_0"
          geometry={nodes.pasted__petal036_petal3_0.geometry}
          material={materials["petal3.004"]}
          position={[0.429, -1.521, 2.726]}
          rotation={[3.111, -0.036, -1.719]}
          scale={0.018}
        />
        <mesh
          name="polySurface1_paper_0"
          geometry={nodes.polySurface1_paper_0.geometry}
          material={materials["paper.004"]}
          scale={0.01}
        />
        <mesh
          name="ribbon2_ribbon1_0"
          geometry={nodes.ribbon2_ribbon1_0.geometry}
          material={materials["ribbon1.004"]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/flower-transformed.glb");
